# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from . import resource

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(905, 610)
        MainWindow.setMinimumSize(QtCore.QSize(905, 610))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/youtube.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.videos = QtWidgets.QWidget()
        self.videos.setObjectName("videos")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.videos)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_4 = QtWidgets.QFrame(self.videos)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.video_label_and_line_edit = QtWidgets.QVBoxLayout()
        self.video_label_and_line_edit.setObjectName("video_label_and_line_edit")
        self.video_id_label = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_id_label.sizePolicy().hasHeightForWidth())
        self.video_id_label.setSizePolicy(sizePolicy)
        self.video_id_label.setObjectName("video_id_label")
        self.video_label_and_line_edit.addWidget(self.video_id_label)
        self.video_id = QtWidgets.QLineEdit(self.frame_4)
        self.video_id.setMinimumSize(QtCore.QSize(500, 0))
        self.video_id.setObjectName("video_id")
        self.video_label_and_line_edit.addWidget(self.video_id)
        self.gridLayout_2.addLayout(self.video_label_and_line_edit, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.qualities = QtWidgets.QComboBox(self.frame_4)
        self.qualities.setObjectName("qualities")
        self.horizontalLayout.addWidget(self.qualities)
        self.load_qualities = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_qualities.sizePolicy().hasHeightForWidth())
        self.load_qualities.setSizePolicy(sizePolicy)
        self.load_qualities.setMinimumSize(QtCore.QSize(190, 0))
        self.load_qualities.setMaximumSize(QtCore.QSize(220, 16777215))
        self.load_qualities.setStyleSheet("")
        self.load_qualities.setObjectName("load_qualities")
        self.horizontalLayout.addWidget(self.load_qualities)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(282, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.download_video = QtWidgets.QPushButton(self.frame_4)
        self.download_video.setMinimumSize(QtCore.QSize(120, 0))
        self.download_video.setObjectName("download_video")
        self.horizontalLayout_5.addWidget(self.download_video)
        spacerItem1 = QtWidgets.QSpacerItem(281, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 5, 0, 1, 2)
        self.download_info = QtWidgets.QVBoxLayout()
        self.download_info.setObjectName("download_info")
        self.currently_downloading = QtWidgets.QLabel(self.frame_4)
        self.currently_downloading.setStyleSheet("margin-top:20;")
        self.currently_downloading.setObjectName("currently_downloading")
        self.download_info.addWidget(self.currently_downloading)
        self.progress_info = QtWidgets.QHBoxLayout()
        self.progress_info.setObjectName("progress_info")
        self.progress = QtWidgets.QProgressBar(self.frame_4)
        self.progress.setEnabled(True)
        self.progress.setAutoFillBackground(False)
        self.progress.setProperty("value", 52)
        self.progress.setAlignment(QtCore.Qt.AlignCenter)
        self.progress.setTextVisible(True)
        self.progress.setOrientation(QtCore.Qt.Horizontal)
        self.progress.setInvertedAppearance(False)
        self.progress.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progress.setObjectName("progress")
        self.progress_info.addWidget(self.progress)
        self.download_info.addLayout(self.progress_info)
        self.gridLayout_2.addLayout(self.download_info, 3, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 6, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 75, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 0, 1, 1, 1)
        self.cancel_aligned = QtWidgets.QFrame(self.frame_4)
        self.cancel_aligned.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cancel_aligned.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cancel_aligned.setObjectName("cancel_aligned")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.cancel_aligned)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.pause_resume = QtWidgets.QPushButton(self.cancel_aligned)
        self.pause_resume.setObjectName("pause_resume")
        self.horizontalLayout_2.addWidget(self.pause_resume)
        self.cancel = QtWidgets.QPushButton(self.cancel_aligned)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_2.addWidget(self.cancel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.gridLayout_2.addWidget(self.cancel_aligned, 4, 0, 1, 2)
        self.gridLayout_9.addWidget(self.frame_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.videos, "")
        self.playlists = QtWidgets.QWidget()
        self.playlists.setObjectName("playlists")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.playlists)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_3 = QtWidgets.QFrame(self.playlists)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.playlist_qualities_label = QtWidgets.QLabel(self.frame_3)
        self.playlist_qualities_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.playlist_qualities_label.setObjectName("playlist_qualities_label")
        self.horizontalLayout_3.addWidget(self.playlist_qualities_label)
        self.playlist_qualities = QtWidgets.QComboBox(self.frame_3)
        self.playlist_qualities.setObjectName("playlist_qualities")
        self.playlist_qualities.addItem("")
        self.playlist_qualities.addItem("")
        self.playlist_qualities.addItem("")
        self.playlist_qualities.addItem("")
        self.horizontalLayout_3.addWidget(self.playlist_qualities)
        self.download_playlist = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download_playlist.sizePolicy().hasHeightForWidth())
        self.download_playlist.setSizePolicy(sizePolicy)
        self.download_playlist.setMinimumSize(QtCore.QSize(180, 0))
        self.download_playlist.setMaximumSize(QtCore.QSize(220, 16777215))
        self.download_playlist.setStyleSheet("")
        self.download_playlist.setObjectName("download_playlist")
        self.horizontalLayout_3.addWidget(self.download_playlist)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.download_info_2 = QtWidgets.QVBoxLayout()
        self.download_info_2.setObjectName("download_info_2")
        self.currently_downloading_playlist_video = QtWidgets.QLabel(self.frame_3)
        self.currently_downloading_playlist_video.setStyleSheet("margin-top:20;")
        self.currently_downloading_playlist_video.setObjectName("currently_downloading_playlist_video")
        self.download_info_2.addWidget(self.currently_downloading_playlist_video)
        self.progress_info_2 = QtWidgets.QHBoxLayout()
        self.progress_info_2.setObjectName("progress_info_2")
        self.playlist_video_progress = QtWidgets.QProgressBar(self.frame_3)
        self.playlist_video_progress.setEnabled(True)
        self.playlist_video_progress.setAutoFillBackground(False)
        self.playlist_video_progress.setProperty("value", 52)
        self.playlist_video_progress.setAlignment(QtCore.Qt.AlignCenter)
        self.playlist_video_progress.setTextVisible(True)
        self.playlist_video_progress.setOrientation(QtCore.Qt.Horizontal)
        self.playlist_video_progress.setInvertedAppearance(False)
        self.playlist_video_progress.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.playlist_video_progress.setObjectName("playlist_video_progress")
        self.progress_info_2.addWidget(self.playlist_video_progress)
        self.download_info_2.addLayout(self.progress_info_2)
        self.gridLayout_3.addLayout(self.download_info_2, 2, 0, 1, 1)
        self.cancel_aligned_2 = QtWidgets.QFrame(self.frame_3)
        self.cancel_aligned_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cancel_aligned_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cancel_aligned_2.setObjectName("cancel_aligned_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.cancel_aligned_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.pause_resume_playlist_video = QtWidgets.QPushButton(self.cancel_aligned_2)
        self.pause_resume_playlist_video.setObjectName("pause_resume_playlist_video")
        self.horizontalLayout_4.addWidget(self.pause_resume_playlist_video)
        self.cancel_playlist_video = QtWidgets.QPushButton(self.cancel_aligned_2)
        self.cancel_playlist_video.setObjectName("cancel_playlist_video")
        self.horizontalLayout_4.addWidget(self.cancel_playlist_video)
        spacerItem7 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.gridLayout_3.addWidget(self.cancel_aligned_2, 3, 0, 1, 1)
        self.video_label_and_line_edit_2 = QtWidgets.QVBoxLayout()
        self.video_label_and_line_edit_2.setObjectName("video_label_and_line_edit_2")
        self.playlist_id_label = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playlist_id_label.sizePolicy().hasHeightForWidth())
        self.playlist_id_label.setSizePolicy(sizePolicy)
        self.playlist_id_label.setObjectName("playlist_id_label")
        self.video_label_and_line_edit_2.addWidget(self.playlist_id_label)
        self.playlist_id = QtWidgets.QLineEdit(self.frame_3)
        self.playlist_id.setMinimumSize(QtCore.QSize(500, 0))
        self.playlist_id.setObjectName("playlist_id")
        self.video_label_and_line_edit_2.addWidget(self.playlist_id)
        self.gridLayout_3.addLayout(self.video_label_and_line_edit_2, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem8 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.stop_downloading_playlist = QtWidgets.QPushButton(self.frame_3)
        self.stop_downloading_playlist.setMinimumSize(QtCore.QSize(240, 0))
        self.stop_downloading_playlist.setObjectName("stop_downloading_playlist")
        self.horizontalLayout_6.addWidget(self.stop_downloading_playlist)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_3, 1, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem10, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem11, 2, 0, 1, 1)
        self.tabWidget.addTab(self.playlists, "")
        self.settings = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(10)
        self.settings.setFont(font)
        self.settings.setStyleSheet("")
        self.settings.setObjectName("settings")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.settings)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_2 = QtWidgets.QFrame(self.settings)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem12 = QtWidgets.QSpacerItem(552, 72, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem12, 0, 0, 1, 3)
        self.videos_location_info = QtWidgets.QGridLayout()
        self.videos_location_info.setObjectName("videos_location_info")
        self.videos_location_browse = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videos_location_browse.sizePolicy().hasHeightForWidth())
        self.videos_location_browse.setSizePolicy(sizePolicy)
        self.videos_location_browse.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.videos_location_browse.setStyleSheet("")
        self.videos_location_browse.setObjectName("videos_location_browse")
        self.videos_location_info.addWidget(self.videos_location_browse, 1, 3, 1, 1)
        self.videos_label_and_line_edit = QtWidgets.QVBoxLayout()
        self.videos_label_and_line_edit.setContentsMargins(-1, 20, -1, -1)
        self.videos_label_and_line_edit.setObjectName("videos_label_and_line_edit")
        self.videos_location_label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videos_location_label.sizePolicy().hasHeightForWidth())
        self.videos_location_label.setSizePolicy(sizePolicy)
        self.videos_location_label.setObjectName("videos_location_label")
        self.videos_label_and_line_edit.addWidget(self.videos_location_label)
        self.videos_location = QtWidgets.QLineEdit(self.frame_2)
        self.videos_location.setMinimumSize(QtCore.QSize(500, 0))
        self.videos_location.setObjectName("videos_location")
        self.videos_label_and_line_edit.addWidget(self.videos_location)
        self.videos_location_info.addLayout(self.videos_label_and_line_edit, 0, 0, 2, 2)
        self.gridLayout_4.addLayout(self.videos_location_info, 2, 0, 1, 3)
        self.playlists_location_info = QtWidgets.QGridLayout()
        self.playlists_location_info.setObjectName("playlists_location_info")
        self.playlists_location_browse = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playlists_location_browse.sizePolicy().hasHeightForWidth())
        self.playlists_location_browse.setSizePolicy(sizePolicy)
        self.playlists_location_browse.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.playlists_location_browse.setStyleSheet("")
        self.playlists_location_browse.setObjectName("playlists_location_browse")
        self.playlists_location_info.addWidget(self.playlists_location_browse, 1, 3, 1, 1)
        self.playlists_label_and_line_edit = QtWidgets.QVBoxLayout()
        self.playlists_label_and_line_edit.setContentsMargins(-1, 20, -1, -1)
        self.playlists_label_and_line_edit.setObjectName("playlists_label_and_line_edit")
        self.playlists_location_label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playlists_location_label.sizePolicy().hasHeightForWidth())
        self.playlists_location_label.setSizePolicy(sizePolicy)
        self.playlists_location_label.setObjectName("playlists_location_label")
        self.playlists_label_and_line_edit.addWidget(self.playlists_location_label)
        self.playlists_location = QtWidgets.QLineEdit(self.frame_2)
        self.playlists_location.setMinimumSize(QtCore.QSize(500, 0))
        self.playlists_location.setObjectName("playlists_location")
        self.playlists_label_and_line_edit.addWidget(self.playlists_location)
        self.playlists_location_info.addLayout(self.playlists_label_and_line_edit, 0, 0, 2, 2)
        self.gridLayout_4.addLayout(self.playlists_location_info, 3, 0, 1, 3)
        spacerItem13 = QtWidgets.QSpacerItem(272, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem13, 4, 0, 1, 1)
        self.save_settings = QtWidgets.QPushButton(self.frame_2)
        self.save_settings.setObjectName("save_settings")
        self.gridLayout_4.addWidget(self.save_settings, 4, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(271, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem14, 4, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(552, 75, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem15, 5, 0, 1, 3)
        self.api_key_info = QtWidgets.QVBoxLayout()
        self.api_key_info.setContentsMargins(-1, 20, -1, -1)
        self.api_key_info.setObjectName("api_key_info")
        self.api_key_label = QtWidgets.QLabel(self.frame_2)
        self.api_key_label.setOpenExternalLinks(True)
        self.api_key_label.setObjectName("api_key_label")
        self.api_key_info.addWidget(self.api_key_label)
        self.api_key = QtWidgets.QLineEdit(self.frame_2)
        self.api_key.setObjectName("api_key")
        self.api_key_info.addWidget(self.api_key)
        self.gridLayout_4.addLayout(self.api_key_info, 1, 0, 1, 3)
        self.gridLayout_7.addWidget(self.frame_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.settings, "")
        self.logs = QtWidgets.QWidget()
        self.logs.setObjectName("logs")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.logs)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame = QtWidgets.QFrame(self.logs)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem16 = QtWidgets.QSpacerItem(20, 190, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem16, 0, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(238, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem17, 1, 0, 1, 1)
        self.logs_hint = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logs_hint.setFont(font)
        self.logs_hint.setObjectName("logs_hint")
        self.gridLayout_5.addWidget(self.logs_hint, 1, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(237, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem18, 1, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 182, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem19, 2, 1, 1, 1)
        self.gridLayout_6.addWidget(self.frame, 0, 0, 1, 1)
        self.tabWidget.addTab(self.logs, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.video_id_label.setBuddy(self.video_id)
        self.playlist_id_label.setBuddy(self.video_id)
        self.videos_location_label.setBuddy(self.video_id)
        self.playlists_location_label.setBuddy(self.video_id)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.video_id.editingFinished.connect(self.video_id.selectAll)
        self.playlist_id.editingFinished.connect(self.playlist_id.selectAll)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.video_id)
        MainWindow.setTabOrder(self.video_id, self.qualities)
        MainWindow.setTabOrder(self.qualities, self.load_qualities)
        MainWindow.setTabOrder(self.load_qualities, self.pause_resume)
        MainWindow.setTabOrder(self.pause_resume, self.cancel)
        MainWindow.setTabOrder(self.cancel, self.download_video)
        MainWindow.setTabOrder(self.download_video, self.playlist_id)
        MainWindow.setTabOrder(self.playlist_id, self.playlist_qualities)
        MainWindow.setTabOrder(self.playlist_qualities, self.download_playlist)
        MainWindow.setTabOrder(self.download_playlist, self.pause_resume_playlist_video)
        MainWindow.setTabOrder(self.pause_resume_playlist_video, self.cancel_playlist_video)
        MainWindow.setTabOrder(self.cancel_playlist_video, self.api_key)
        MainWindow.setTabOrder(self.api_key, self.videos_location)
        MainWindow.setTabOrder(self.videos_location, self.videos_location_browse)
        MainWindow.setTabOrder(self.videos_location_browse, self.playlists_location)
        MainWindow.setTabOrder(self.playlists_location, self.playlists_location_browse)
        MainWindow.setTabOrder(self.playlists_location_browse, self.save_settings)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YT Downloader"))
        self.video_id_label.setText(_translate("MainWindow", "Video URL/ID"))
        self.video_id.setPlaceholderText(_translate("MainWindow", "https://www.youtube.com/watch?v=kq89VPwFMOY"))
        self.label.setText(_translate("MainWindow", "Video Quality"))
        self.load_qualities.setText(_translate("MainWindow", "Load availabe video qualites"))
        self.download_video.setText(_translate("MainWindow", "Download"))
        self.currently_downloading.setText(_translate("MainWindow", "Downloading __________"))
        self.pause_resume.setText(_translate("MainWindow", "Pause"))
        self.cancel.setText(_translate("MainWindow", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.videos), _translate("MainWindow", "Video"))
        self.playlist_qualities_label.setText(_translate("MainWindow", "What to download"))
        self.playlist_qualities.setItemText(0, _translate("MainWindow", "1. Highest quality progressive video"))
        self.playlist_qualities.setItemText(1, _translate("MainWindow", "2. Highest quality audio"))
        self.playlist_qualities.setItemText(2, _translate("MainWindow", "3. Highest quality audio and video seperately"))
        self.playlist_qualities.setItemText(3, _translate("MainWindow", "4. 3+merge (ffmpeg required) [merging might take a long time]-NOT RECOMENDED"))
        self.download_playlist.setText(_translate("MainWindow", "Start Downloading"))
        self.currently_downloading_playlist_video.setText(_translate("MainWindow", "Downloading __________"))
        self.pause_resume_playlist_video.setText(_translate("MainWindow", "Pause"))
        self.cancel_playlist_video.setText(_translate("MainWindow", "Cancel"))
        self.playlist_id_label.setText(_translate("MainWindow", "Playlist URL/ID"))
        self.playlist_id.setPlaceholderText(_translate("MainWindow", "https://www.youtube.com/playlist?list=PLYf4Vz9V1ESrVD_NMDlwRjgo8jn2UNEND"))
        self.stop_downloading_playlist.setText(_translate("MainWindow", "Stop Downloading Playlist"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.playlists), _translate("MainWindow", "Playlist"))
        self.videos_location_browse.setText(_translate("MainWindow", "Browse"))
        self.videos_location_label.setText(_translate("MainWindow", "Location to save videos"))
        self.videos_location.setPlaceholderText(_translate("MainWindow", "C:\\Users\\Public\\Videos\\YouTube\\Videos"))
        self.playlists_location_browse.setText(_translate("MainWindow", "Browse"))
        self.playlists_location_label.setText(_translate("MainWindow", "Location to save playlists"))
        self.playlists_location.setPlaceholderText(_translate("MainWindow", "C:\\Users\\Public\\Videos\\YouTube\\Playlists"))
        self.save_settings.setText(_translate("MainWindow", "Save"))
        self.api_key_label.setText(_translate("MainWindow", "Youtube API key (Required to download playlists) <a href=\"https://github.com/Iftakharpy/YT-Downloader\">Get an API key</a>"))
        self.api_key.setPlaceholderText(_translate("MainWindow", "AIzaSyA4BwZtGYkc-4n9xqaE8kDfCgHvVn5gjgI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), _translate("MainWindow", "Settings"))
        self.logs_hint.setText(_translate("MainWindow", "I might add this in the future"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logs), _translate("MainWindow", "Logs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
